oSldX[argument0, argument1] = argument2
oSldY[argument0, argument1] = argument3
oSldW[argument0, argument1] = argument4
oSldStart[argument0, argument1] = argument5
oSldEnd[argument0, argument1] = argument6
oSldNotches[argument0, argument1] = argument7
oSldValue[argument0, argument1] = argument8
oSldPos[argument0, argument1] = getOptionSliderPosition(argument0, argument1)
oSldName[argument0, argument1] = argument9
oSldDesc[argument0, argument1] = argument10
tabSliders[argument0] += 1
