var keyIn;
keyIn = argument0
switch keyIn
{
    case 32:
        return "Space";
    case 16:
        return "Shift";
    case 17:
        return "Ctrl";
    case 18:
        return "Alt";
    case 13:
        return "Enter";
    case 38:
        return "Up";
    case 40:
        return "Down";
    case 37:
        return "Left";
    case 39:
        return "Right";
    case 8:
        return "BSpace";
    case 9:
        return "Tab";
    case 45:
        return "Insert";
    case 46:
        return "Delete";
    case 33:
        return "PgUp";
    case 34:
        return "PgDn";
    case 36:
        return "Home";
    case 35:
        return "End";
    case 27:
        return "Esc";
    case 44:
        return "PrntScr";
    case 112:
        return "F1";
    case 113:
        return "F2";
    case 114:
        return "F3";
    case 115:
        return "F4";
    case 116:
        return "F5";
    case 117:
        return "F6";
    case 118:
        return "F7";
    case 119:
        return "F8";
    case 120:
        return "F9";
    case 121:
        return "F10";
    case 122:
        return "F11";
    case 123:
        return "F12";
    case 160:
        return "L.Shift";
    case 161:
        return "R.Shift";
    case 162:
        return "L.Ctrl";
    case 163:
        return "R.Ctrl";
    case 164:
        return "L.Alt";
    case 165:
        return "R.Alt";
    case 96:
        return "0";
    case 97:
        return "1";
    case 98:
        return "2";
    case 99:
        return "3";
    case 100:
        return "4";
    case 101:
        return "5";
    case 102:
        return "6";
    case 103:
        return "7";
    case 104:
        return "8";
    case 105:
        return "9";
    case 106:
        return "*";
    case 107:
        return "+";
    case 109:
        return "-";
    case 110:
        return ".";
    case 111:
        return "/";
    case 186:
        return ";";
    case 187:
        return "=";
    case 188:
        return ",";
    case 189:
        return "-";
    case 190:
        return ".";
    case 191:
        return "/";
    case 192:
        return "`";
    case 219:
        return "[";
    case 220:
        return "\";
    case 221:
        return "]";
    case 222:
        return "'";
    default:
        return chr(keyIn);
}

