ini_open("config.ini")
ini_write_real("Settings", "Mute_music", global.muteMusic)
ini_write_real("Settings", "Volume_level", global.volumeLevel)
ini_write_real("Settings", "Fullscreen_mode", global.fullscreenMode)
ini_write_real("Settings", "Smoothing_mode", global.smoothingMode)
ini_write_real("Settings", "Vsync_mode", global.vsyncMode)
ini_write_real("Controls", "Left", global.leftButton[0])
ini_write_real("Controls", "Right", global.rightButton[0])
ini_write_real("Controls", "Up", global.upButton[0])
ini_write_real("Controls", "Down", global.downButton[0])
ini_write_real("Controls", "Jump", global.jumpButton[0])
ini_write_real("Controls", "Undo", global.shootButton[0])
ini_write_real("Controls", "Restart", global.restartButton[0])
ini_write_real("Controls", "Skip", global.skipButton[0])
ini_write_real("Controls", "Pause", global.pauseButton[0])
ini_write_real("Controls", "Camera", global.camButton[0])
ini_write_real("Controls", "Action", global.masButton[0])
if global.controllerEnabled
{
    ini_write_real("Controller", "Index", global.controllerIndex)
    ini_write_real("Controller", "Left", global.leftButton[1])
    ini_write_real("Controller", "Right", global.rightButton[1])
    ini_write_real("Controller", "Up", global.upButton[1])
    ini_write_real("Controller", "Down", global.downButton[1])
    ini_write_real("Controller", "Jump", global.jumpButton[1])
    ini_write_real("Controller", "Undo", global.shootButton[1])
    ini_write_real("Controller", "Restart", global.restartButton[1])
    ini_write_real("Controller", "Skip", global.skipButton[1])
    ini_write_real("Controller", "Pause", global.pauseButton[1])
    ini_write_real("Controller", "Camera", global.camButton[1])
    ini_write_real("Controller", "Action", global.masButton[1])
}
ini_close()
