var i;
ini_open("config.ini")
ini_write_real("Part2Check", "Check", 1)
ini_write_real("Sound", "Mute_music", global.muteMusic)
ini_write_real("Sound", "Volume_level", global.volumeLevel)
ini_write_real("Sound", "Sound_level", global.soundLevel)
ini_write_real("Sound", "Music_level", global.musicLevel)
ini_write_real("Visual", "Fullscreen_mode", global.fullscreenMode)
ini_write_real("Visual", "Smoothing_mode", global.smoothingMode)
ini_write_real("Visual", "Vsync_mode", global.vsyncMode)
ini_write_real("Visual", "windowScale", global.windowScale)
ini_write_real("Visual", "lowFX", global.lowFX)
ini_write_real("Visual", "simpleLock", global.simpleLock)
ini_write_real("Visual", "pauseStyle", global.pauseStyle)
for (i = 0; i < 14; i += 1)
{
    ini_write_real("Colors", ("darkTone" + string(i)), global.darkTone[i])
    ini_write_real("Colors", ("mainTone" + string(i)), global.mainTone[i])
    ini_write_real("Colors", ("highTone" + string(i)), global.highTone[i])
}
ini_write_real("Colorblind", "useSymbols", global.useSymbols)
ini_write_real("Colorblind", "doHighlight", global.doHighlight)
ini_write_real("Colorblind", "filter", global.filter)
ini_write_real("Accessibility", "hideTime", global.hideTime)
ini_write_real("Accessibility", "runSwitch", global.runSwitch)
ini_write_real("Accessibility", "fullJumps", global.fullJumps)
ini_write_real("Accessibility", "allUnlock", global.allUnlock)
ini_write_real("Controls", "Left", global.leftButton[0])
ini_write_real("Controls", "Right", global.rightButton[0])
ini_write_real("Controls", "Up", global.upButton[0])
ini_write_real("Controls", "Down", global.downButton[0])
ini_write_real("Controls", "Jump", global.jumpButton[0])
ini_write_real("Controls", "Undo", global.shootButton[0])
ini_write_real("Controls", "Restart", global.restartButton[0])
ini_write_real("Controls", "Skip", global.skipButton[0])
ini_write_real("Controls", "Pause", global.pauseButton[0])
ini_write_real("Controls", "Camera", global.camButton[0])
ini_write_real("Controls", "Action", global.masButton[0])
ini_write_real("Controls", "Leave", global.leaveButton[0])
ini_write_real("Controls", "Warp", global.warpButton[0])
ini_write_real("Controls", "Special", global.specialButton[0])
ini_write_real("Controls", "Runswitch", global.rsButton[0])
ini_write_real("Controls", "Run", global.runButton[0])
ini_write_real("Controls", "Walk", global.walkButton[0])
ini_write_real("Controls", "Select", global.selButton[0])
ini_write_real("Controls", "Interact", global.intrButton[0])
if global.controllerEnabled
{
    ini_write_real("Controller", "Index", global.controllerIndex)
    ini_write_real("Controller", "Left", global.leftButton[1])
    ini_write_real("Controller", "Right", global.rightButton[1])
    ini_write_real("Controller", "Up", global.upButton[1])
    ini_write_real("Controller", "Down", global.downButton[1])
    ini_write_real("Controller", "Jump", global.jumpButton[1])
    ini_write_real("Controller", "Undo", global.shootButton[1])
    ini_write_real("Controller", "Restart", global.restartButton[1])
    ini_write_real("Controller", "Skip", global.skipButton[1])
    ini_write_real("Controller", "Pause", global.pauseButton[1])
    ini_write_real("Controller", "Camera", global.camButton[1])
    ini_write_real("Controller", "Action", global.masButton[1])
    ini_write_real("Controller", "Leave", global.leaveButton[1])
    ini_write_real("Controller", "Warp", global.warpButton[1])
    ini_write_real("Controller", "Special", global.specialButton[1])
    ini_write_real("Controller", "Runswitch", global.rsButton[1])
    ini_write_real("Controller", "Run", global.runButton[1])
    ini_write_real("Controller", "Walk", global.walkButton[1])
    ini_write_real("Controller", "Select", global.selButton[1])
    ini_write_real("Controller", "Interact", global.intrButton[1])
}
ini_close()
